{{- if .Values.ingress.enabled -}}
{{- $architecture := .Values.architecture }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          {{- if eq $architecture "high-availability" }}
          - path: /write
            backend:
              serviceName: {{ include "common.names.fullname" $ }}-relay
              servicePort: http
          {{- end }}
          - path: /*
            backend:
              serviceName: {{ include "common.names.fullname" $ }}
              servicePort: http
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
