{{- if and .Values.influxdb.configuration (not .Values.influxdb.existingConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
data:
  influxdb.conf: |-
    # User-supplied configuration:
    {{ include "common.tplvalues.render" (dict "value" .Values.influxdb.configuration "context" $) | indent 4 }}
