{{- if and (eq .Values.architecture "high-availability") .Values.relay.configuration (not .Values.relay.existingConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-relay
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: relay
data:
  relay.toml: |-
    {{ include "common.tplvalues.render" (dict "value"  .Values.relay.configuration "context" $) | indent 4 }}
{{- end }}
